server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  profiles:
    active: default
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
#    mvc:
#      servlet:
#        path: /api/v1
